### ISSUE TITLE
Describe how to filter out several tags

### ISSUE THREAD

**Issue by greg0ire** [Behat/docs#88]
The documentation shows how to filter out one tag : 

``` yaml
default:
    gherkin:
        filters:
            tags: ~@mytag
```

Now when I try to use an array as a value for `tags`, I get an error saying `tags` should be scalar. But it has an s, so I think it should allow arrays too… can't find the correct syntax though.
